import asyncio
from typing import Any

from telethon import TelegramClient, events
from telethon.errors import (
    AuthKeyError,
    FloodWaitError,
    RPCError,
    SessionPasswordNeededError,
)
from telethon.tl.types import Message, PeerUser

from ai.agent import NexusBrain
from core.config import settings
from database.connection import AsyncSessionLocal
from database.models import Task
from utils.logger import logger


class TelegramAutomator:
    """
    Telegram bot daemon for the NEXUS assistant.

    Responsibilities
    ----------------
    1. Connect to Telegram using the bot token supplied in settings.
    2. Listen for every incoming private message **or** any message that
       contains the trigger word "nexus" (case-insensitive).
    3. Reply instantly with a response generated by ``NexusBrain``.
    4. Simultaneously fire a non-blocking background task that extracts a
       structured task from the same message and persists it to PostgreSQL.
    """

    _TRIGGER_WORD: str = "nexus"

    def __init__(self, brain: NexusBrain) -> None:
        self._brain = brain
        # Use /tmp so the session file is always writable on any host
        self._client = TelegramClient(
            session="/tmp/nexus_bot_session",
            api_id=settings.TELEGRAM_API_ID,
            api_hash=settings.TELEGRAM_API_HASH,
        )
        self._register_handlers()
        logger.info(
            "TelegramAutomator created (api_id={})", settings.TELEGRAM_API_ID
        )

    # ── Handler registration ──────────────────────────────────────────────────

    def _register_handlers(self) -> None:
        """Attach all Telethon event handlers to the client."""

        @self._client.on(events.NewMessage(incoming=True))
        async def _on_new_message(event: events.NewMessage.Event) -> None:
            await self._handle_message(event)

    # ── Core message handler ──────────────────────────────────────────────────

    async def _handle_message(self, event: events.NewMessage.Event) -> None:
        """
        Route an incoming Telegram event.

        Fires only when:
        - The message is from a private (one-to-one) conversation, OR
        - The message text contains the trigger word "nexus".
        """
        message: Message = event.message
        text: str = (message.text or "").strip()

        if not text:
            return

        is_private: bool = isinstance(message.peer_id, PeerUser)
        mentions_nexus: bool = self._TRIGGER_WORD in text.lower()

        if not (is_private or mentions_nexus):
            return

        chat_id: int = message.chat_id or 0
        sender_id: int = message.sender_id or 0

        logger.info(
            "Incoming message | chat={} sender={} private={} nexus_mention={}",
            chat_id,
            sender_id,
            is_private,
            mentions_nexus,
        )

        try:
            # ── 1. Generate AI reply (awaited — user is waiting for this) ──
            reply_text: str = await self._brain.generate_response(text)
            await event.reply(reply_text)
            logger.debug("Reply sent | chat={} length={}", chat_id, len(reply_text))
        except FloodWaitError as exc:
            logger.warning(
                "Telegram flood-wait: {} seconds. Skipping reply.", exc.seconds
            )
            return
        except RPCError as exc:
            logger.error("Telegram RPC error while replying: {}", exc)
            return
        except Exception as exc:
            logger.exception("Unexpected error while replying: {}", exc)
            return

        # ── 2. Background task extraction (non-blocking) ───────────────────
        asyncio.create_task(
            self._extract_and_save_task(text),
            name=f"task_extract_chat{chat_id}",
        )

    # ── Background task persistence ───────────────────────────────────────────

    async def _extract_and_save_task(self, text: str) -> None:
        """
        Extract a task from ``text`` using the AI brain and persist it to
        PostgreSQL if ``has_task`` is True.

        This coroutine is always run as an ``asyncio.create_task`` so it
        never blocks the response path.
        """
        try:
            result: dict[str, Any] = await self._brain.extract_tasks(text)

            if not result.get("has_task"):
                logger.debug(
                    "_extract_and_save_task | no task found in: {!r:.80}", text
                )
                return

            title: str = (result.get("title") or "").strip()
            description: str | None = (result.get("description") or "").strip() or None

            if not title:
                logger.warning(
                    "_extract_and_save_task | has_task=True but title is empty"
                )
                return

            async with AsyncSessionLocal() as session:
                task = Task(title=title, description=description)
                session.add(task)
                await session.commit()
                await session.refresh(task)

            logger.success(
                "Task saved | id={} title={!r}", task.id, task.title
            )

        except Exception as exc:
            logger.exception(
                "_extract_and_save_task | unhandled error: {}", exc
            )

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        """
        Connect to Telegram and start the event-dispatch loop.

        This coroutine runs until the process is shut down (it calls
        ``client.run_until_disconnected`` internally).  Designed to be
        launched as ``asyncio.create_task(ta.start())`` from the FastAPI
        startup event so it runs concurrently with the HTTP server.
        """
        logger.info("Connecting to Telegram…")
        try:
            await self._client.start(bot_token=settings.TELEGRAM_BOT_TOKEN)
            me = await self._client.get_me()
            logger.success(
                "Telegram connected | bot=@{} id={}", me.username, me.id
            )
            await self._client.run_until_disconnected()
        except AuthKeyError:
            logger.critical(
                "Telegram auth key is invalid. "
                "Delete the session file and reconfigure credentials."
            )
            raise
        except SessionPasswordNeededError:
            logger.critical(
                "Two-factor authentication is enabled but no password was provided."
            )
            raise
        except Exception as exc:
            logger.exception("Telegram daemon crashed: {}", exc)
            raise

    async def stop(self) -> None:
        """Gracefully disconnect the Telegram client."""
        if self._client.is_connected():
            await self._client.disconnect()
            logger.info("Telegram client disconnected.")
